version: '3.9'

services:

  postgresql:
    image: postgres:16.0-alpine3.18
    container_name: postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    init: true
    ports:
      - "5432:5432"
    volumes:
      - ./.local/postgresql/data/:/var/lib/postgresql/data/:rw
    healthcheck:
      test: pg_isready -U "${DB_USERNAME}" || exit 1
      interval: 15s
      retries: 6
      start_period: 6s
      timeout: 6s

  parser:
    build:
      context: .
    container_name: parser
    env_file:
      - .env
    image: parser:latest
    init: true
    depends_on:
      postgresql:
        condition: service_healthy